id: A16949997
base_file: f30E2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:04:22.357274
  last_modified_at: 2022-06-05 20:04:22.357280
